### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
```
FB: Running: appstreamcli compose --no-partial-urls --prefix=/ --origin=org.kde.massif-visualizer --media-baseurl=https://dl.flathub.org/media --media-dir=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-FZvBZf/files/share/app-info/media --result-root=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-FZvBZf/files --data-dir=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-FZvBZf/files/share/app-info/xmls --icons-dir=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-FZvBZf/files/share/app-info/icons/flatpak '--components=org.kde.massif-visualizer,org.kde.massif-visualizer.desktop' /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-FZvBZf/files
Only accepting components: org.kde.massif-visualizer, org.kde.massif-visualizer.desktop
Processing directory: /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-FZvBZf/files
Composing metadata...
Run failed, some data was ignored.
Errors were raised during this compose run:
general
  E: filters-but-no-output
Refer to the generated issue report data for details on the individual problems.
```

**Comment by travier** [comment]
Trying to add a category: https://invent.kde.org/sdk/massif-visualizer/-/merge_requests/18

**Comment by travier** [comment]
I don't know how I can reproduce this issue. From https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/:

```
$ flatpak run --command=flatpak-builder-lint org.flatpak.Builder appstream app/files/share/metainfo/org.kde.massif-visualizer.metainfo.xml
✔ Validation was successful.
```

**Comment by travier** [comment]
@bbhtt How do you debug those issues?

**Comment by bbhtt** [comment]
The ID tag in appdata does not match Flatpak ID, dash vs. underscore

image

**Comment by bbhtt** [comment]
If the ID actually changed, you probably want to resubmit and EOL rebase this. https://docs.flathub.org/docs/for-app-authors/maintenance#renaming-the-flatpak-id

**Comment by travier** [comment]
Hum, the launchable is still using the old name: https://invent.kde.org/sdk/massif-visualizer/-/blob/master/app/org.kde.massif-visualizer.appdata.xml?ref_type=heads#L364

**Comment by travier** [comment]
https://invent.kde.org/sdk/massif-visualizer/-/commit/31c03d01a4576715dc723a8ee28167b1c9ea6217

**Comment by travier** [comment]
OK, let's temporarily keep the old name.

**Pull request merged**
